# Generated by Django 5.0.1 on 2024-01-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "bookno",
                    models.IntegerField(
                        db_column="bookNo", primary_key=True, serialize=False
                    ),
                ),
                (
                    "bookname",
                    models.CharField(
                        blank=True, db_column="bookName", max_length=20, null=True
                    ),
                ),
                (
                    "bookauthor",
                    models.CharField(
                        blank=True, db_column="bookAuthor", max_length=10, null=True
                    ),
                ),
                (
                    "bookprice",
                    models.IntegerField(blank=True, db_column="bookPrice", null=True),
                ),
                (
                    "bookdate",
                    models.DateField(blank=True, db_column="bookDate", null=True),
                ),
                (
                    "bookstock",
                    models.IntegerField(blank=True, db_column="bookStock", null=True),
                ),
            ],
            options={
                "db_table": "book",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Booksale",
            fields=[
                (
                    "bsno",
                    models.IntegerField(
                        db_column="bsNo", primary_key=True, serialize=False
                    ),
                ),
                ("bsdate", models.DateField(blank=True, db_column="bsDate", null=True)),
                (
                    "bsqty",
                    models.IntegerField(blank=True, db_column="bsQty", null=True),
                ),
            ],
            options={
                "db_table": "bookSale",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "clientno",
                    models.IntegerField(
                        db_column="clientNo", primary_key=True, serialize=False
                    ),
                ),
                (
                    "clientname",
                    models.CharField(
                        blank=True, db_column="clientName", max_length=10, null=True
                    ),
                ),
                (
                    "clientphone",
                    models.CharField(
                        blank=True, db_column="clientPhone", max_length=13, null=True
                    ),
                ),
                (
                    "clientaddress",
                    models.CharField(
                        blank=True, db_column="clientAddress", max_length=20, null=True
                    ),
                ),
                (
                    "clientbirth",
                    models.DateField(blank=True, db_column="clientBirth", null=True),
                ),
                (
                    "clienthobby",
                    models.CharField(
                        blank=True, db_column="clientHobby", max_length=10, null=True
                    ),
                ),
                (
                    "clientgender",
                    models.CharField(
                        blank=True, db_column="clientGender", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "client",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prd_no", models.CharField(max_length=10)),
                ("prd_name", models.CharField(blank=True, max_length=20, null=True)),
                ("prd_price", models.IntegerField(blank=True, null=True)),
                ("prd_maker", models.CharField(blank=True, max_length=30, null=True)),
                ("prd_color", models.CharField(blank=True, max_length=10, null=True)),
                ("ctg_no", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "product",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "pubno",
                    models.IntegerField(
                        db_column="pubNo", primary_key=True, serialize=False
                    ),
                ),
                (
                    "pubname",
                    models.CharField(
                        blank=True, db_column="pubName", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "publisher",
                "managed": False,
            },
        ),
    ]
